name: .NET Core Tests and CodeQL Security Analysis

on:
  [ push, pull_request ]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    
    - name: Build and run Unit Tests with dotnet
      run: dotnet test --framework net5.0 --configuration Release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
